# Generated by Django 5.0.6 on 2024-06-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_photo',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
