# Generated by Django 5.0.6 on 2024-06-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_main_photo'),
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='avaible_sizes',
            field=models.ManyToManyField(related_name='products', to='sizes.size'),
        ),
    ]
